### ISSUE TITLE
Last cell is missing y_test values

### ISSUE THREAD

**Issue by ebtezcan** [learn-co-curriculum/dsc-introduction-to-neural-networks-lab#3]
The final cell where the model is run is missing the y_test argument (test_labels_final). The code should read as follows:

# ⏰ Expect your code to take several minutes to run
output = model(train_img_final, train_labels_final, test_img_final, test_labels_final,
               num_iterations=2000, learning_rate=0.005, print_cost=True)

**Comment by kjspring** [comment]
Still has this issue.

**Comment by bpurdy-ds** [comment]
Thanks, and fixed. Closed with commit: https://github.com/learn-co-curriculum/dsc-introduction-to-neural-networks-lab/issues/3#issue-915163005.
