### ISSUE TITLE
Cannot import Keras packages in lesson 

### ISSUE THREAD

**Issue by JM-Hansen** [learn-co-curriculum/dsc-introduction-to-neural-networks-lab#5]
## Link to Canvas

https://learning.flatironschool.com/courses/5318/assignments/189542?module_item_id=422857

## Issue Subtype

- [ X] Master branch code
- [ ] Solution branch code
- [ ] Code tests
- [ ] Layout/rendering issue
- [ ] Instructions unclear
- [ ] Other (explain below)

### Source

```
from keras.preprocessing.image import ImageDataGenerator, load_img, array_to_img, img_to_array 
```

### Concern

This throws an error, cannot load packages

## (Optional) Proposed Solution

Instead of keras.preprocessing.image use ----> keras_preprocessing.image
notice use of underscore, this will properly load the packages

## What OS Are You Using?

- [X ] OS X
- [ ] Windows
- [ ] WSL
- [ ] Linux
- [ ] Saturn Cloud from Canvas

**Comment by christine-egan42** [comment]
tested this code and I am able to import Keras using:
`from keras.preprocessing.image import ImageDataGenerator`
Note that this is after I performed the conda re-install as per Brendan's instructions [here](https://github.com/learn-co-curriculum/dsc-tf-m1).
